### ISSUE TITLE
Add support for Joi 6.x.x

### ISSUE THREAD

**Issue by lancespeelmon** [hapijs/good#348]
hello I am trying to upgrade joi from 5.1.0 to 6.x and get this warning:
`npm WARN unmet dependency /Develop/trax/document-service/node_modules/good requires joi@'5.x.x' but will load`
but when I hit: 
```
server.register({
   register: require('good'),
```
I get: 
```
TypeError: undefined is not a function`
   at Object.<anonymous> (/Develop/trax/document-service/node_modules/good/lib/schema.js:21:28)
```
Is there a workaround or do you think it warrants a github issue?
[10:06am] nlf: lancespeelmon: try updating your installation of good
I think I have done that - here is where my depds are: https://gist.github.com/aa7fb43f63f1ea2d4c55
i.e.    `"good": "^6.1.3",`
Here is the line that bombs: `    reporters: Joi.array().includes(Joi.object(), Joi.string()).required().min(1),`
There are other Joi references before that line - so must be a joi 5.x/6.x compat issue

**Comment by arb** [comment]
I don't know what this is supposed to be. Please open readable issues.

**Comment by lancespeelmon** [comment]
Sorry - that was from the IRC channel...

**Comment by arb** [comment]
I need more information. The version of Joi you are using in your own project should be completely independent of the version Good is using.

**Comment by lancespeelmon** [comment]
That is what I thought too... but when I upgrade join from 5.1.0 to 6.x, I get this error.

**Comment by arb** [comment]
There must be some environmental thing happening that causes this. Otherwise, there would have been several issues like this long before now.

**Comment by lancespeelmon** [comment]
FYI
```
Darwin localhost 14.4.0 Darwin Kernel Version 14.4.0: Tue May 12 21:00:42 PDT 2015; root:xnu-2782.30.4~4/RELEASE_X86_64 x86_64
node --version && npm --version
v0.12.4
2.10.1
```

**Comment by lancespeelmon** [comment]
Comment from @Marsup on #349 
>That's what happens when you work on modules individually, had you reinstalled all your dependencies with that same package.json you would not have had the problem. This should be addressed by npm 3 in the future.

**Comment by lancespeelmon** [comment]
@Marsup I am not sure I understand what you are suggesting exactly other than to wait on npm 3. If there is something I could do in the mean time, could you please be a bit more specific? Thanks!!!! L :smile:

**Comment by Marsup** [comment]
Remove all your node_modules and reinstall.

**Comment by lancespeelmon** [comment]
Thanks @Marsup that got me past that error and on to a new stack trace that looks unrelated to good.
